# -*- coding: utf-8 -*-
"""Project on (Content-Based-Movie-Recommendation-System) Codec Technologies

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1jjE9nhTEipOdn6Xe0722RoYSFZFb1-fi
"""

import pandas as pd
import numpy as np
import seaborn as sns

import zipfile

with zipfile.ZipFile('/content/Content-Based-Movie-Recommendation-System-master.zip') as z:
    print(z.namelist())

['Content-Based-Movie-Recommendation-System-master/movies.csv', '...']

import zipfile
import pandas as pd

zip_path = '/content/Content-Based-Movie-Recommendation-System-master.zip'

with zipfile.ZipFile(zip_path, 'r') as z:
    with z.open('Content-Based-Movie-Recommendation-System-master/movie_dataset.csv') as f:
        df = pd.read_csv(f)

print(df.head())

df.head()

df.tail()

df.shape

df.describe()

df.iloc()

df.iloc[40,1]

df.isnull().sum()

df.dropna(axis=1,inplace=True)
df.head()

new_df=df.dropna()
new_df.head()

df.head()

df.info()

print(df.columns)

sns.countplot(data=df, x='popularity')

sns.jointplot(x="budget", y="revenue", data=df)

df.info()

sns.countplot(x="production_companies", data=df)

sns.jointplot(x="vote_average", y="vote_count",data = df)

import zipfile
import pandas as pd
import matplotlib.pyplot as plt

# Check if the necessary columns exist
if 'budget' in df.columns and 'revenue' in df.columns:
    plt.figure(figsize=(10, 6))
    df.plot.scatter(x='budget', y='revenue', alpha=0.5)
    plt.title('Budget vs. Revenue')
    plt.xlabel('Budget')
    plt.ylabel('Revenue')
    plt.grid(True)
    plt.show()
else:
    print("One or both columns 'budget' and 'revenue' do not exist in the DataFrame.")

# Check if the necessary columns exist
if 'budget' in df.columns and 'revenue' in df.columns:
    plt.figure(figsize=(10, 6))
    df.plot.scatter(x='budget', y='revenue', alpha=0.5)
    plt.title('Budget vs. Revenue')
    plt.xlabel('Budget')
    plt.ylabel('Revenue')
    plt.grid(True)
    plt.show()
else:
    print("One or both columns 'budget' and 'revenue' do not exist in the DataFrame.")

import pandas as pd

def create_dataframe():
    data = {'titles': [10, 20, 40, 50]}
    df = pd.DataFrame(data)
    return df

# Call the function and assign the result to df
df = create_dataframe()

# Now you can perform operations on df
for x in df.index:
    if df.loc[x, "titles"] > 30:
        df.drop(x, inplace=True)

df.head()

print(df.duplicated())

missing_values = df.isnull()
print(missing_values)

missing_count_per_column = df.isnull().sum()
print(missing_count_per_column)

import missingno as msno
import matplotlib.pyplot as plt

msno.matrix(df)
plt.show()