# -*- coding: utf-8 -*-
"""project on (Data_Analysis_on_Weather_Dataset) Codec Technologies

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1Doc8bJ9x9DmZwgZozftQCcxKvsuc9I7n
"""

!pip install pandas

"""Data Importing and Preprocessing"""

import pandas as pd
import zipfile

# Path to the ZIP archive
zip_file_path = '/content/Data_Analysis_on_Weather_Dataset-main.zip'

# Name of the CSV file within the ZIP archive
csv_filename = 'Data_Analysis_on_Weather_Dataset-main/1. Weather Data.csv'

# Open the ZIP archive
with zipfile.ZipFile(zip_file_path, 'r') as z:
    # Open the specific CSV file
    with z.open(csv_filename) as f:
        # Read the CSV file into a DataFrame
        df = pd.read_csv(f)

# Display the DataFrame
print(df)

import pandas as pd
import numpy as np
import seaborn as sns
import matplotlib.pyplot as plt

df.head(10)

df.tail(10)

df.iloc[30,1]

import os
print(os.getcwd())

new_df = df.dropna()
new_df.head()

df.describe()

with zipfile.ZipFile(zip_file_path, 'r') as z:
      print(z.namelist())

df.Weather.unique()

df.count()

df.value_counts()

df.info()

df.shape

df.describe()

df.fillna(120,inplace=True)
df.head()

for x in df.index:
  if df.loc[x,"Temp_C"] >30:
    df.drop(x,inplace=True)
df.head()

print(df.duplicated())

df.drop_duplicates(inplace=True)
df.head()

print(df.columns)

sns.jointplot(x='Temp_C', y='Dew Point Temp_C', data=df)

print(df.columns)

df.head()

sns.jointplot(x="Wind Speed_km/h", y="Visibility_km", data=df)

df.head(10)

sns.countplot(x="Visibility_km", data=df)

import pandas as pd
import zipfile
import matplotlib.pyplot as plt

import os

zip_file_path = '/content/Data_Analysis_on_Weather_Dataset-main.zip'
if not os.path.exists(zip_file_path):
    print(f"File not found: {zip_file_path}")

import pandas as pd
import zipfile

# Path to the ZIP archive
zip_file_path = '/content/Data_Analysis_on_Weather_Dataset-main.zip'

# Name of the CSV file within the ZIP archive
csv_filename = 'Data_Analysis_on_Weather_Dataset-main/1. Weather Data.csv'

# Open the ZIP archive
with zipfile.ZipFile(zip_file_path, 'r') as z:
    # Open the specific CSV file
    with z.open(csv_filename) as f:
        # Read the CSV file into a DataFrame
        df = pd.read_csv(f)

# Display the DataFrame
print(df)

# Convert 'Date/Time' column to datetime format and set as index
df['Date/Time'] = pd.to_datetime(df['Date/Time'])
df.set_index('Date/Time', inplace=True)

# Path to the ZIP archive
zip_file_path = '/content/Data_Analysis_on_Weather_Dataset-main.zip'

# Name of the CSV file within the ZIP archive
csv_filename = 'Data_Analysis_on_Weather_Dataset-main/1. Weather Data.csv'

# Open the ZIP archive and read the CSV file into a DataFrame
with zipfile.ZipFile(zip_file_path, 'r') as z:
    with z.open(csv_filename) as f:
        df = pd.read_csv(f)

print(df.columns.tolist())

df.columns = df.columns.str.strip()

df.rename(columns={'Temperature (C)': 'Temperature_C'}, inplace=True)

temperature = df.get('Temperature (C)')
if temperature is not None:
    # Proceed with operations
    print("Temperature data is available.")

def function():
    pass

print(df.columns)

print(df.head())

df.columns = df.columns.str.strip()

wind_speed = df.get('Wind Speed (km/h)')
if wind_speed is None:
    print("Column 'Wind Speed (km/h)' does not exist.")

print(df.columns[df.columns.duplicated()])

import pandas as pd

# Load your DataFrame
# df = pd.read_csv('/content/Data_Analysis_on_Weather_Dataset-main.zip')

# Check the columns
print("Columns in DataFrame:")
print(df.columns)

# Strip whitespace from column names
df.columns = df.columns.str.strip()

# Check for the specific column
if 'Temperature (C)' in df.columns:
    print("Column 'Temperature (C)' exists.")
else:
    print("Column 'Temperature (C)' does not exist.")

import pandas as pd
import zipfile
import matplotlib.pyplot as plt

# Path to the ZIP archive
zip_file_path = '/content/Data_Analysis_on_Weather_Dataset-main.zip'

# Name of the CSV file within the ZIP archive
csv_filename = 'Data_Analysis_on_Weather_Dataset-main/1. Weather Data.csv'

# Open the ZIP archive
with zipfile.ZipFile(zip_file_path, 'r') as z:
    # Open the specific CSV file
    with z.open(csv_filename) as f:
        # Read the CSV file into a DataFrame
        df = pd.read_csv(f)

# Display the DataFrame
print(df.head())  # Display the first few rows of the DataFrame

# Check the columns in the DataFrame
print("Columns in DataFrame:")
print(df.columns)

# Strip whitespace from column names
df.columns = df.columns.str.strip()

# Check if the required columns exist
if 'Temperature (C)' in df.columns and 'Wind Speed (km/h)' in df.columns:
    # Plotting the data
    plt.figure(figsize=(12, 6))

    # Plot Temperature
    plt.subplot(1, 2, 1)  # 1 row, 2 columns, 1st subplot
    plt.plot(df['Temperature (C)'], color='blue', label='Temperature (C)')
    plt.title('Temperature Over Time')
    plt.xlabel('Index')
    plt.ylabel('Temperature (C)')
    plt.legend()
    plt.grid()

    # Plot Wind Speed
    plt.subplot(1, 2, 2)  # 1 row, 2 columns, 2nd subplot
    plt.plot(df['Wind Speed (km/h)'], color='orange', label='Wind Speed (km/h)')
    plt.title('Wind Speed Over Time')
    plt.xlabel('Index')
    plt.ylabel('Wind Speed (km/h)')
    plt.legend()
    plt.grid()

    # Show the plots
    plt.tight_layout()
    plt.show()
else:
    print("Required columns are not present in the DataFrame.")